apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-05T13:50:42Z"
  labels:
    app: prueba-web-deployment
  name: prueba-web-deployment
  namespace: default
  resourceVersion: "4942"
  uid: 8014a146-8dc5-4516-bb37-06362be58221
spec:
  clusterIP: 10.96.241.194
  clusterIPs:
  - 10.96.241.194
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32695
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: prueba-web-deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
