apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2023-08-05T13:50:19Z"
  generation: 5
  labels:
    app: prueba-web-deployment
  name: prueba-web-deployment
  namespace: default
  resourceVersion: "9031"
  uid: a0d51218-c2d5-4299-8cbe-1670a1aeeedc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prueba-web-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-08-05T12:21:10-03:00"
      creationTimestamp: null
      labels:
        app: prueba-web-deployment
    spec:
      containers:
      - image: williamsoft/prueba_web:v2
        imagePullPolicy: Always
        name: prueba-web-kwqt2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-08-05T13:57:57Z"
    lastUpdateTime: "2023-08-05T13:57:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-08-05T13:50:19Z"
    lastUpdateTime: "2023-08-05T15:21:14Z"
    message: ReplicaSet "prueba-web-deployment-7bc9975967" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
